---

// Координаты спавна X,Y,Z
Spawn: 0,0,0

// Координаты арены для первого игрока X,Y,Z
1: 0,0,0
// 1 и 2 точка арены, для её очистки. (в виде кубоида)
1a: 0,0,0
1b: 0,0,0


// Координаты арены для второго игрока X,Y,Z
2: 0,0,0
// 1 и 2 точка арены, для её очистки. (в виде кубоида)
2a: 0,0,0
2b: 0,0,0

// Координаты арены для третьего игрока X,Y,Z
3: 0,0,0
// 1 и 2 точка арены, для её очистки. (в виде кубоида)
3a: 0,0,0
3b: 0,0,0

// Координаты арены для четвертого игрока X,Y,Z
4: 0,0,0
// 1 и 2 точка арены, для её очистки. (в виде кубоида)
4a: 0,0,0
4b: 0,0,0

// Координаты арены для пятого игрока X,Y,Z
5: 0,0,0
// 1 и 2 точка арены, для её очистки. (в виде кубоида)
5a: 0,0,0
5b: 0,0,0

...
